# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: 디스코드 알림봇

on:
  schedule: # UTC+9 기준 10시 50분 실행
    - cron:  "50 1 * * 3"

jobs:
  message:
    runs-on: ubuntu-latest
    steps:
    - name: Discord Webhook Action
      uses: tsickert/discord-webhook@v5.3.0
      with:
        webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
        content: "잠시 후에 하루코테 모임이 시작됩니다 ☺️"

